
#server
server:
  port: 9012
  servlet:
    context-path: /api
#数据库
spring:
  servlet:
    multipart:
      # 上传文件总的最大值
      max-file-size: 30MB
      # 单个文件的最大值
      max-request-size: 5MB
  application:
    name: watermelonhit_blog
  datasource:
    url: jdbc:mysql://112.74.190.84:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: "Su985211"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 112.74.190.84
    port: 6380
    password: Sus985211
#mybatis-plus
mybatis-plus:
  configuration: #打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_